
services:
  source_postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      - POSTGRES_DB=source_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1724
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  destination_postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      - POSTGRES_DB=destination_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1724

  elt_replicator:
    build:
      context: ./elt
      dockerfile: Dockerfile
    command: ["python", "elt_runner.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres
    environment:
      SOURCE_DB_NAME: source_db
      SOURCE_DB_USER: root
      SOURCE_DB_PASSWORD: 1724
      SOURCE_DB_HOST: source_postgres
      SOURCE_DB_PORT: 5432
      DESTINATION_DB_NAME: destination_db
      DESTINATION_DB_USER: root
      DESTINATION_DB_PASSWORD: 1724
      DESTINATION_DB_HOST: destination_postgres
      DESTINATION_DB_PORT: 5432

  dbt:
    build:
      context: .
      dockerfile:  Dockerfile.dbt
    command: >
      bash -c "
        echo '⏳ Waiting for destination_postgres to be ready...' &&
        until pg_isready -h destination_postgres -U root; do sleep 2; done &&
        echo '✅ Database ready, running dbt...' &&
        dbt run --profiles-dir /root/.dbt --project-dir /usr/app/postgres_elt_dbt
      "
    networks:
      - elt_network
    volumes:
      - ./postgres_elt_dbt:/usr/app/postgres_elt_dbt
      - ~/.dbt:/root/.dbt

    depends_on:
      - elt_replicator

    environment:
      DBT_PROFILE: default
      DBT_TARGET: dev
    
networks:
  elt_network:
    driver: bridge
